apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gqnf7b4qv-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gqnf7b4qv-java-springboot-gitops